# Generated by Django 6.0.4 on 2026-04-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pharmacies', '0002_alter_pharmacy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pharmacy'], name='accounts_us_pharmac_b66fff_idx'),
        ),
    ]
