# Generated by Django 4.2.30 on 2026-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_inventory_batch_number_inventory_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
