# Generated by Django 4.2.30 on 2026-04-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_alter_pharmacy_payment_receipt_and_more'),
        ('medicines', '0006_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pharmacies.pharmacy'),
        ),
        migrations.AlterField(
            model_name='review',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='medicines.medicine'),
        ),
    ]
