# Generated by Django 4.2.30 on 2026-04-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_review_pharmacy_alter_review_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_ocr_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
