# Generated by Django 6.0.4 on 2026-04-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='location_name',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='subscription_status',
        ),
    ]
