# Generated by Django 4.2.30 on 2026-04-17 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPharmacyInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stockout_risk_count', models.IntegerField(default=0)),
                ('predicted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('most_sold_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.globalmedicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='pharmacies.pharmacy')),
            ],
            options={
                'indexes': [models.Index(fields=['pharmacy', 'date'], name='analytics_d_pharmac_244871_idx')],
                'unique_together': {('pharmacy', 'date')},
            },
        ),
    ]
