# Generated by Django 6.0.4 on 2026-04-17 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPharmacyInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stockout_risk_count', models.IntegerField(default=0)),
                ('predicted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
