# Generated by Django 6.0.4 on 2026-04-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('inventory', '0003_globalmedicine_and_more'),
        ('pharmacies', '0003_pharmacy_address_pharmacy_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypharmacyinsights',
            name='most_sold_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.globalmedicine'),
        ),
        migrations.AddField(
            model_name='dailypharmacyinsights',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='pharmacies.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='dailypharmacyinsights',
            index=models.Index(fields=['pharmacy', 'date'], name='analytics_d_pharmac_244871_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypharmacyinsights',
            unique_together={('pharmacy', 'date')},
        ),
    ]
