# Generated by Django 4.2.30 on 2026-04-20 09:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='location_lon',
        ),
        migrations.CreateModel(
            name='PharmacyLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sector', models.CharField(choices=[('Sikela', 'Sikela'), ('Secha', 'Secha'), ('Other', 'Other')], default='Sikela', max_length=50)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='pharmacies.pharmacy')),
            ],
        ),
    ]
