# Generated by Django 4.2.30 on 2026-04-22 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0002_remove_pharmacy_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='last_inventory_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pharmacies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verification_doc',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
