# Generated by Django 4.2.30 on 2026-04-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_pharmacy_last_inventory_sync_pharmacy_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='pharmacies/receipts/'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='verification_doc',
            field=models.FileField(blank=True, null=True, upload_to='pharmacies/licenses/'),
        ),
    ]
