# Generated by Django 4.2.30 on 2026-04-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_pharmacy_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='payment_receipt',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='verification_doc',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
