# Generated by Django 4.2.30 on 2026-04-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_alter_pharmacy_payment_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='subscription_tier',
            field=models.CharField(default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='trial_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
