# Generated by Django 4.2.30 on 2026-04-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0006_remove_pharmacy_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
