# Generated by Django 4.2.30 on 2026-04-17 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Global Medicines',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_stock_level', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_at_pharmacies', to='inventory.globalmedicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.AddIndex(
            model_name='globalmedicine',
            index=models.Index(fields=['generic_name'], name='inventory_g_generic_52dd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['pharmacy'], name='inventory_i_pharmac_bfe5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['pharmacy', 'medicine'], name='inventory_i_pharmac_6ad3e8_idx'),
        ),
    ]
