# Generated by Django 6.0.4 on 2026-04-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pharmacies', '0002_alter_pharmacy_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['pharmacy'], name='inventory_i_pharmac_bfe5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['pharmacy'], name='inventory_m_pharmac_2436f3_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['sku'], name='inventory_m_sku_f55e64_idx'),
        ),
    ]
