# Generated by Django 6.0.4 on 2026-04-17 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_inventory_i_pharmac_bfe5a6_idx_and_more'),
        ('pharmacies', '0003_pharmacy_address_pharmacy_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Global Medicines',
            },
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='inventory_m_pharmac_2436f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='inventory_m_sku_f55e64_idx',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='quantity_on_hand',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pharmacies.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='globalmedicine',
            index=models.Index(fields=['generic_name'], name='inventory_g_generic_52dd8b_idx'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_at_pharmacies', to='inventory.globalmedicine'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['pharmacy', 'medicine'], name='inventory_i_pharmac_6ad3e8_idx'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pharmacy',
        ),
    ]
