# Generated by Django 6.0.4 on 2026-04-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_globalmedicine_and_more'),
        ('sales', '0003_remove_sale_medicine_remove_sale_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
