# Generated by Django 6.0.4 on 2026-04-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_inventory_i_pharmac_bfe5a6_idx_and_more'),
        ('pharmacies', '0002_alter_pharmacy_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['pharmacy'], name='sales_sale_pharmac_bef14f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_sale_created_e208b3_idx'),
        ),
    ]
