# Generated by Django 4.2.30 on 2026-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='detected_medicines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
